apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: homework-3
spec:
  interval: 15m
  chart:
    spec:
      chart: mongodb
      version: 13.6.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    architecture: "replicaset"
    usePassword: true
    auth:
      existingSecret: mongodb-secret
    service:
      type: ClusterIP
    resourcesArbiter:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    persistence:
      enabled: true
      size: 8Gi
