apiVersion: v1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: homework-3
spec:
  chart:
    spec:
      chart: mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: homework-3
  values:
    replicaSet:
      enabled: true
    usePassword: true
    existingSecret: mongodb-secret
    service:
      type: ClusterIP
    resourcesArbiter:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    persistence:
      enabled: true
      size: 8Gi
