apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: homework-3
spec:
  releaseName: nginx
  interval: 15m
  chart:
    spec:
      chart: nginx
      version: 15.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    replicaCount: 1
    service:
      type: NodePort
      port: 80
      nodePort: 30080
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
