apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: homework-3
spec:
  interval: 5m
  chart:
    spec:
      chart: rabbitmq
      version: 12.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    auth:
      existingSecret: rabbitmq-secret
      updatePassword: true
      existingPasswordSecret: rabbitmq-secret
      existingUsernameSecret: rabbitmq-secret
      usernameSecretKey: rabbitmq-username
      passwordSecretKey: rabbitmq-password
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    persistence:
      enabled: true
