apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: homework-3
spec:
  interval: 15m
  chart:
    spec:
      chart: rabbitmq
      version: 12.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    auth:
      updatePassword: true
      username: user
      password: homework3
      # existingPasswordSecret: rabbitmq-secret
      # existingSecretPasswordKey: rabbitmq-password
      # existingErlangSecret: rabbitmq-secret
      # existingSecretErlangKey: rabbitmq-erlang-cookie
    service:
      type: ClusterIP
      ports:
        amqp: 5672
        manager: 15672
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    persistence:
      enabled: true
