apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: homework-3
spec:
  interval: 15m
  chart:
    spec:
      chart: rabbitmq
      version: 12.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  values:
    auth:
      username: user
      # password: homework3
      # erlangCookie: 3kKzAV2cYrJjB9L3fD3ZmNXNCBkg9q8D
      existingPasswordSecret: rabbitmq-secret
      existingErlangSecret: rabbitmq-secret
    service:
      type: ClusterIP
      ports:
        amqp: 5672
        manager: 15672
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    persistence:
      enabled: true
      size: 1Gi
