apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb-exporter
  namespace: homework-3
spec:
  releaseName: mongodb-exporter
  interval: 5m
  chart:
    spec:
      chart: mongodb-exporter
      version: "7.4.6" # hoặc phiên bản mới
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    mongodb:
      uri: "mongodb://root:homework3@mongodb-headless.homework-3.svc.cluster.local:27017"
    service:
      port: 9216
      type: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
