apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: homework-3
spec:
  releaseName: kube-prometheus-stack
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "56.0.0" # hoặc version mới nhất
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      adminPassword: "admin"
      service:
        type: ClusterIP
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
